name: Build WDA for iOS15.8
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Switch to iOS15 branch
        run: git checkout ios-16-and-below
      - name: Replace Bundle ID
        run: sed -i '' "s/com.facebook.WebDriverAgentRunner/${{ secrets.BUNDLE_ID }}/g" WebDriverAgent.xcodeproj/project.pbxproj
      - name: Build WDA
        run: xcodebuild build-for-testing -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination generic/platform=iOS CODE_SIGN_IDENTITY="Apple Development" DEVELOPMENT_TEAM=${{ secrets.TEAM_ID }} PRODUCT_BUNDLE_IDENTIFIER=${{ secrets.BUNDLE_ID }}
      - name: Package IPA
        run: |
          mkdir Payload
          cp -r build/Release-iphoneos/WebDriverAgentRunner-Runner.app Payload/
          zip -r WDA.ipa Payload
      - name: Upload WDA.ipa
        uses: actions/upload-artifact@v4
        with:
          name: WDA-iOS15
          path: WDA.ipa
